eureka:
  client:
    enabled: false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://review-db:5432/review_db}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
