server:
  port: 8084

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://localhost:5432/review_db
    username: postgres
    password: 29102005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true